# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('travel_from', models.DateField()),
                ('travel_to', models.DateField()),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.User')),
                ('user', models.ManyToManyField(related_name='events', to='loginapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=50)),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.User')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Event')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.Event'),
        ),
    ]
